# Generated by Django 4.2.11 on 2025-01-14 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_customuser_email"),
    ]

    operations = [
        migrations.DeleteModel(name="PageView",),
        migrations.AddField(
            model_name="customuser",
            name="password",
            field=models.CharField(
                default=1234, max_length=128, verbose_name="password"
            ),
            preserve_default=False,
        ),
    ]
