# Generated by Django 4.2.11 on 2025-01-14 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_delete_pageview_customuser_password"),
    ]

    operations = [
        migrations.AlterModelManagers(name="customuser", managers=[],),
        migrations.AddField(
            model_name="customuser",
            name="username",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
